name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore zaersara-release.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias zaersara \
            -storepass ZaerSara2026Strong \
            -keypass ZaerSara2026Strong \
            -dname "CN=Zaersara Mashhad, OU=Android, O=Zaersara, L=Mashhad, ST=Khorasan, C=IR"

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: zaersara-release-keystore
          path: zaersara-release.jks
